#!/usr/bin/env zsh

eval "$(starship init zsh)"

plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-history-substring-search"

plug "zdharma-continuum/fast-syntax-highlighting"
plug "hlissner/zsh-autopair"

# plug "zap-zsh/zap-prompt"
plug "zap-zsh/completions"
plug "zap-zsh/fnm"
plug "zap-zsh/supercharge"
plug "zap-zsh/vim"
plug "zap-zsh/exa" # WARNING: needs to be loaded after supercharge
plug "lukechilds/zsh-better-npm-completion"
plug "MichaelAquilina/zsh-you-should-use"

eval "$(mcfly init zsh)"
