#!/bin/sh
HISTFILE=~/.cache/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

eval "$(mcfly init zsh)"
eval "$(fnm env)"
# eval "`pip completion --zsh`"

export MANPAGER='lvim +Man!'
export MANWIDTH=999
export MCFLY_RESULTS=30
export MCFLY_KEY_SCHEME=vim

export PATH=$HOME/.fnm:$PATH
export PATH="$(yarn global bin):$PATH"
export PATH="$HOME/.local/share/cargo/bin:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
        . "$HOME/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
