#!/usr/bin/env zsh

if [ -d "/opt/homebrew" ]; then
  eval $(/opt/homebrew/bin/brew shellenv)
fi

plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-history-substring-search"

plug "zdharma-continuum/fast-syntax-highlighting"
plug "hlissner/zsh-autopair"

plug "zap-zsh/exa"
plug "zap-zsh/zap-prompt"

eval "$(mcfly init zsh)"
eval "$(fnm env)"
