#!/bin/sh
HISTFILE="$ZDOTDIR/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000

eval "$(mcfly init zsh | sed "s,\^R,^H,")"
eval "$(fnm env)"

export MANPAGER="$EDITOR +Man!"
export MANWIDTH=999
export MCFLY_KEY_SCHEME=vim
