#!/usr/bin/env zsh

# Key bindings
bindkey -s '^o' '^u${CLI_FILE_EXPLORER}\n' # open
bindkey -s '^b' '^u${GUI_FILE_EXPLORER} .\n' # browse
bindkey -s '^g' '^u${CLI_GIT_APP}\n' # git
bindkey -s '^s' '^u${CLI_DOCKER_APP}\n'
bindkey -s '^f' '^ucd "$(dirname "$(fzf)")"\n' # find

# nr command = (npm|yarn|pnpm) run # @antfu/ni
bindkey -s '^d' '^unr dev\n' 
bindkey -s '^x' '^unr\n' 

bindkey '^[[A' history-substring-search-up # arrow up
bindkey '^[[B' history-substring-search-down # arrow down

bindkey '^[[P' delete-char

# Emacs bindings
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^p' history-substring-search-up
bindkey '^n' history-substring-search-down

# VIM del char in visual and normal modes
bindkey -M vicmd '^[[P' vi-delete-char
bindkey -M visual '^[[P' vi-delete

# Change cursor shape for different VIM modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}
