#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
  df="df -h" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
  cat="bat" \
	ls="exa -la -F --time-style=iso --icons --group-directories-first --git" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="sudo shutdown -h now" \
	e="sudoedit" \
	v="$EDITOR" \
	p="sudo pacman" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	wth="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"




##
## My aliases
##

# yarn
alias \
    yr="yarn" \
    yra="yarn add" \
    yrr="yarn remove" \
    yri="yarn install" \
    yrd="yarn dev" \
    yrb="yarn build" \
    yrs="yarn start" \
    yrt="yarn test" \
    yrf="yarn info --verbose --no-emoji"

# php
alias \
    paws="php artisan websockets:serve" \
    cs="composer" \
    csr="composer refresh" \
    csb="composer rebuild" \
    csi="composer install" \
    sail="~/.config/composer/vendor/bin/sail"

# valet
alias \
    va="valet" \
    vas="valet secure" \
    vau="valet unsecure" \
    var="valet restart" \
    vad="valet domain" \
    val="valet link" \
    vaf="valet forget" \
    vau="valet use" \
    vast="valet status"

# systemctl
alias \
  sctl="sudo systemctl" \
  sctle="sudo systemctl enable" \
  sctld="sudo systemctl disable" \
  sctlr="sudo systemctl restart"
  sctlst="sudo systemctl status" \
  sctlsr="sudo systemctl start" \
  sctlsp="sudo systemctl stop" \
  sctlfl="sudo systemctl --failed

# youtube
alias \
  ytd="yt -x -f bestaudio/best --download-archive playlist.txt" \
  ytdg="mg; yt -x -f bestaudio/best --download-archive playlist.txt 'https://www.youtube.com/playlist?list=PLqQefq-YNypMfVRJJSW10MRaFYARFiL_P'" \
  ytdl="ml; yt -x -f bestaudio/best --download-archive playlist.txt 'https://www.youtube.com/playlist?list=PLqQefq-YNypOJjVTvYXW-8ftq2GpnxXVV'" \
  ytdo="mo; yt -x -f bestaudio/best --download-archive playlist.txt 'https://www.youtube.com/playlist?list=PLqQefq-YNypOhI67WpGJVJyXyBem_VOYZ'" \
  ytda="ma; yt -x -f bestaudio/best --download-archive playlist.txt 'https://www.youtube.com/playlist?list=PLqQefq-YNypNxKSWAsR7VQxEY63RK7AwD'" \
  ytdall="ytdg; ytdl; ytdo; ytda" \
  rkrl="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"

# sync
alias \
  ssrc="sdw && g pl && cmpl; sdb && g pl && cmpl; sdm && g pl && cmpl; sst && g pl && cmpl" \
  sconf="ca && g pl; cg && g pl; cu && g pl; cv && g pl" \
  sproj="pd && g pl; pz && g pl; pza && g pl;" \
  sall="ssrc; sconf; sproj"

# misc
alias \
  gcl="dmenu-github" \
  cmpl="sudo make && sudo make install"
