#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	bc="bc -ql" \
  df="df -h" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="exa -F --time-style=iso --icons --group-directories-first --git" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
  t="tree"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="sudo shutdown -h now" \
	e="sudoedit" \
	v="$EDITOR" \
	p="sudo pacman" \
  pkgs="pkgstats search"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	wth="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"




##
## My aliases
##

# yarn
alias \
    yr="yarn" \
    yra="yarn add" \
    yrr="yarn remove" \
    yri="yarn install" \
    yrd="yarn dev" \
    yrb="yarn build" \
    yrs="yarn start" \
    yrt="yarn test" \
    yrp="yarn prod" \
    yrf="yarn info --verbose --no-emoji"

# php
alias \
    paws="sudo php artisan websockets:serve --host=0.0.0.0 --port=444" \
    cs="composer" \
    csi="composer install" \
    csr="composer refresh" \
    csb="composer rebuild" \
    csd="composer deploy" \
    csa="csi; csr; csb; csd;" \
    sail="~/.config/composer/vendor/bin/sail"

# valet
alias \
    va="valet" \
    vas="valet secure" \
    vau="valet unsecure" \
    var="valet restart" \
    vad="valet domain" \
    val="valet link" \
    vaf="valet forget" \
    vau="valet use" \
    vast="valet status"

# systemctl
alias \
  sctl="sudo systemctl" \
  sctle="sudo systemctl enable" \
  sctld="sudo systemctl disable" \
  sctlr="sudo systemctl restart" \
  sctlst="sudo systemctl status" \
  sctlsr="sudo systemctl start" \
  sctlsp="sudo systemctl stop" \
  sctlfl="sudo systemctl --failed"

# youtube
alias \
  ytd="yt -x -f bestaudio/best --download-archive playlist.txt" \
  ytdg="mg; yt -x -f bestaudio/best --download-archive playlist.txt 'https://www.youtube.com/playlist?list=PLqQefq-YNypMfVRJJSW10MRaFYARFiL_P'" \
  ytdl="ml; yt -x -f bestaudio/best --download-archive playlist.txt 'https://www.youtube.com/playlist?list=PLqQefq-YNypOJjVTvYXW-8ftq2GpnxXVV'" \
  ytdo="mo; yt -x -f bestaudio/best --download-archive playlist.txt 'https://www.youtube.com/playlist?list=PLqQefq-YNypOhI67WpGJVJyXyBem_VOYZ'" \
  ytda="ma; yt -x -f bestaudio/best --download-archive playlist.txt 'https://www.youtube.com/playlist?list=PLqQefq-YNypNxKSWAsR7VQxEY63RK7AwD'" \
  ytdall="ytdg; ytdl; ytdo; ytda" \
  rkrl="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"

# sync
alias \
  replace-basic="
    rm ~/{.zprofile,.xprofile} &&
    rm -rf ~/.config/{dunst,fontconfig,gtk-3.0,gtk-2.0,lf,mpd,mpv,ncmpcpp,newsboat,nvim,pulse,shell,sxiv,wal,wget,x11,zathura,zsh,neofetch} &&
    rm ~/.config/{mimeapps.list,user-dirs.dirs} &&
    rm -rf ~/.local/share/{applications,larbs}
  " \
  replace-needed="
    rm -rf ~/.local/bin/{cron,statusbar} &&
    rm ~/.local/bin/* | echo 'y' &&
    cd ~/.config/personal && stow --adopt --target=/home/jakub arch voidrice &&
    rm -rf ~/.local/bin/{cron,statusbar} &&
    mkdir ~/.local/bin/{statusbar,cron} &&
    ln -n ~/.config/personal/voidrice/.local/bin/statusbar/* ~/.local/bin/statusbar/ &&
    ln -n ~/.config/personal/voidrice/.local/bin/cron/* ~/.local/bin/cron/ &&
    cd ~/.config/personal && stow --adopt --target=/home/jakub universal
  " \
  replace-all="replace-basic; replace-needed" \
  ssrc="sdw && g pl && cmpl; sdb && g pl && cmpl; sdm && g pl && cmpl; sst && g pl && cmpl" \
  sdots="ca && g pl; cg && g pl; cu && g pl; cv && g pl" \
  sproj="pd && g pl; pz && g pl; pza && g pl;" \
  sconf="ssrc; sdots; replace-needed" \
  sall="ssrc; sdots; sproj; replace-all"

# misc
alias \
  gcl="dmenu-github" \
  cmpl="sudo make && sudo make install" \
  ff="cd $HOME/.mozilla/firefox/*.dev-edition-default" \
  ffc="cd $HOME/.mozilla/firefox/*.dev-edition-default/chrome" \
  ggl="tuxi" \
  myip="curl ifconfig.co" \
  update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
  encrypt="gpg -c --no-symkey-cache --cipher-algo AES256" \
  pack="tar -zcvf"
