#!/bin/zsh
# NOTE: read once, at login (variables and settings that don't need to be updated frequently)

source $HOME/.config/shell/profile.all

if [[ $OSTYPE == 'linux'* ]]; then
	source $HOME/.config/shell/profile.linux
else
	source $HOME/.config/shell/profile.osx
fi

unsetopt PROMPT_SP

bin_list=(
  "$(yarn global bin)"
  "$HOME/.local/share/cargo/bin"
  )

for extra in "${bin_list[@]}"; do
  PATH=$extra:$PATH
done
export PATH
unset bin_list
