#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			           # set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
mpd &			             # music player daemon-you might prefer it as a service though
remaps &		           # run the remaps script, switching caps/esc and more; check it for more info
# xcompmgr &		       # xcompmgr for transparency
picom --experimental-backend &		             # picom for transparency and blur
dunst &			           # dunst for notifications
xset r rate 250 50 &	 # Speed xrate up
unclutter &		         # Remove mouse when idle
fcitx -d &             # Keyboard
# pulseeffects --gapplication-service &         # Equalizer
redshift &             # Night light
/usr/lib/kdeconnectd & # KDE connect daemon
# dropbox &            # Dropbox
