#!/bin/bash

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Wallpaper with some wal arguments
setbg "" "false" &			                               

# Xresources colors/settings on startup
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	 

# Switching caps/esc, adjusting speed, etc...
remaps &		                                                         

autostart="
$AUTOSTART_PROGRAMS
$ADDITIONAL_AUTOSTART_PROGRAMS
"
printf "%s" "$autostart" | while IFS="" read -r program; do
	pgrep -fl "$program" || $program &
done >/dev/null 2>&1

# Weird thingy needed for Kinto to work
# xhost +SI:localuser:root &

# Screen layouts
if [[ $LAYOUT_TYPE ]]; then
  eval "layout-${LAYOUT_TYPE}"
fi

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
