#!/usr/bin/env bash
# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

# To edit this file copy it to `${HOME}/.config/dmscripts/config`
# `cp /etc/dmscripts/config ${HOME}/.config/dmscripts/config`

# Defined variables, modify anything in quotes to your prefered software

DMENU="dmenu"
# DMENU="rofi -dmenu"

# dm-confedit
# confedit_editor="$EDITOR"
# declare -A confedit_list
# confedit_list[confedit]="$HOME/.config/dmscripts/config"
# confedit_list[alacritty]="$HOME/.config/alacritty/alacritty.yml"
# confedit_list[awesome]="$HOME/.config/awesome/rc.lua"
# confedit_list[bash]="$HOME/.bashrc"
# confedit_list[broot]="$HOME/.config/broot/conf.toml"
# confedit_list[bspwm]="$HOME/.config/bspwm/bspwmrc"
# confedit_list[doom emacs config.el]="$HOME/.config/doom/config.el"
# confedit_list[doom emacs config.org]="$HOME/.config/doom/config.org"
# confedit_list[doom emacs init.el]="$HOME/.config/doom/init.el"
# confedit_list[doom emacs packages.el]="$HOME/.config/doom/packages.el"
# confedit_list[dunst]="$HOME/.config/dunst/dunstrc"
# confedit_list[dwm]="$HOME/dwm-distrotube/config.def.h"
# confedit_list[dwmblocks]="$HOME/dwmblocks-distrotube/blocks.def.h"
# confedit_list[fish]="$HOME/.config/fish/config.fish"
# confedit_list[herbstluftwm]="$HOME/.config/herbstluftwm/autostart"
# confedit_list[i3]="$HOME/.config/i3/config"
# confedit_list[ncmpcpp]="$HOME/.config/ncmpcpp/config"
# confedit_list[neovim]="$HOME/.config/nvim/init.vim"
# confedit_list[picom]="$HOME/.config/picom/picom.conf"
# confedit_list[polybar]="$HOME/.config/polybar/config"
# confedit_list[qtile]="$HOME/.config/qtile/config.py"
# confedit_list[qutebrowser bookmarks]="$HOME/.config/qutebrowser/bookmarks/urls"
# confedit_list[qutebrowser quickmarks]="$HOME/.config/qutebrowser/quickmarks"
# confedit_list[qutebrowser config.py]="$HOME/.config/qutebrowser/config.py"
# confedit_list[spectrwm]="$HOME/.spectrwm.conf"
# confedit_list[ssh]="$HOME/.ssh/config"
# confedit_list[st]="$HOME/st-distrotube/config.def.h"
# confedit_list[stumpwm]="$HOME/.config/stumpwm/config"
# confedit_list[surf]="$HOME/surf-distrotube/config.def.h"
# confedit_list[sxhkd]="$HOME/.config/sxhkd/sxhkdrc"
# confedit_list[tabbed]="$HOME/tabbed-distrotube/config.def.h"
# confedit_list[vifm]="$HOME/.config/vifm/vifmrc"
# confedit_list[vim]="$HOME/.vimrc"
# confedit_list[xmobar mon1]="$HOME/.config/xmobar/xmobarrc0"
# confedit_list[xmobar mon2]="$HOME/.config/xmobar/xmobarrc1"
# confedit_list[xmobar mon3]="$HOME/.config/xmobar/xmobarrc2"
# confedit_list[xmonad]="$HOME/.xmonad/README.org"
# confedit_list[xinitrc]="$HOME/.xinitrc"
# confedit_list[xresources]="$HOME/.Xresources"
# confedit_list[zsh]="$HOME/.zshrc"

# Search engine config
websearch_browser="$BROWSER"
declare -A websearch
# Syntax:
# websearch[name]="https://www.example.com/search?q="

# Information/News
websearch[wikipedia]="https://en.wikipedia.org/w/index.php?search="
websearch[wiktionary]="https://en.wiktionary.org/w/index.php?search="
websearch[maps]="https://www.google.com/maps/search/"
# Social Media
websearch[reddit]="https://www.reddit.com/search/?q="
websearch[youtube]="https://www.youtube.com/results?search_query="
# Linux
websearch[archwiki]="https://wiki.archlinux.org/index.php?search="
# Development
websearch[github]="https://github.com/search?q="
websearch[stackoverflow]="https://stackoverflow.com/search?q="
websearch[caniuse]="https://caniuse.com/?search="
websearch[npmjs]="https://www.npmjs.com/search?q=vue"
websearch[bundlephobia]="https://bundlephobia.com/package/"
# Japanese
websearch[kanji]="https://jisho.org/search/%23kanji"
websearch[jisho]="https://jisho.org/search/"
# Etc

# dm-translate
declare -A translate_list
translate_list[english]="en"
translate_list[japanese]="ja"
translate_list[polish]="pl"

_revision=13
