[hyprbars]
description = "A plugin to add title bars to windows"
version = "1.0"
author = "Vaxry"

[hyprbars.build]
output = "hyprbars/hyprbars.so"
steps = [
    "make -C hyprbars all",
]

[hyprfocus]
description = "a plugin which provides focus animations for us borderless folks, originally inspired by flashfocus"
version = "2.0"
author = "Vortex"

[hyprfocus.build]
output = "hyprfocus.so"
steps = [
    "make all",
]
