[general]
import = ["/home/jakub/.config/alacritty/themes/alacritty-theme/themes/gruvbox_light.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.offset]
x = 0
y = -1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Insert"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[window]
decorations = "none"
opacity = 0.96
option_as_alt = "Both"

[window.dimensions]
columns = 200
lines = 50
