[general]
import = ["~/.config/alacritty/themes/alacritty-theme/themes/gruvbox_light.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.offset]
x = -1
y = -3


[window]
decorations = "buttonless"
opacity = 0.96
option_as_alt = "Both"
